language: node_js
services:
  - docker
node_js:
  - 13
install:
  - docker build --rm -f docker/Dockerfile -t luissaybe/connect-4-reinforcement-learning-js .
script:
  - echo 'hello'
deploy:
  provider: script
  script: bash docker/push.bash
  on:
    branch: master
